### PR TITLE
Master

### PR DESCRIPTION
**Pull request by VirRus77**
Little refactoring.
Translation of logging to basic logging through Microsoft.Extensions.Logging.Abstractions.
Highlighting a library with basic functionality.

### CODE REVIEW

**Comment by VirRus77** [comment]
The main commentary to the source: the reduction of characters.
When you are alone on a project, yes. If not, don't cut it =)

**Comment by Donkie** [comment]
Closing this because #9 contains this commit as well.

**Comment by Donkie** [comment]
actually nvm i'll just merge this first

**Comment by VirRus77** [comment]
The I3Decriptor carries a logical rationale: in one part, working with the key itself, in the other, working with the data key.
Accordingly, the Load method in ShapesFile is left temporarily. In the future, it will be deleted and will need to work only with Entity. Because only this feature allows you to download information from maps using small memory.
How I use: https://github.com/VirRus77/CourseplayEditor/blob/d1547fd2d1ea3c95a59c92cc60a469e1610bb33a/CourseplayEditor/ViewModel/MainWindowViewModel.cs#L162

**Pull request merged**
