### PR TITLE
Master

### PR DESCRIPTION
**Pull request by VirRus77**
Convert to new version csproj file.

### CODE REVIEW

**Comment by Donkie** [comment]
This breaks dependencies and achieves nothing

**Comment by VirRus77** [comment]
This is a preliminary preparation of the project for the allocation of functionality in a separate library under netcorestandard.

Translated from Google Translate.

**Comment by Donkie** [comment]
Alright, but it still breaks dependencies and the unit testing environment

**Comment by VirRus77** [comment]
What version of VisualStuio are you using?

**Comment by Donkie** [comment]
2017 Community.

**Comment by VirRus77** [comment]
Good. I will redo it for 2017.
Just 2019 normally opens and produces UnitTests.

Translated from Google Translate.

**Pull request closed without merging**
