### PR TITLE
Changed to the new version of csproj.

### PR DESCRIPTION
**Pull request by VirRus77**
With working tests:
image

### CODE REVIEW

**Comment by Donkie** [comment]
@VirRus77 I have converted the project to .NET Core 3.1 (I'm using VS 2019 now) now. Hope it helps!

**Comment by VirRus77** [comment]
@Donkie At the moment, I would use 2.0...

**Comment by Donkie** [comment]
Any reason why specifically 2.0? 2.1 is the LTS version, I'd rather support that.

**Comment by VirRus77** [comment]
It is possible and 2.1. Simply, if you do the nuget package, not everyone will agree to update the net core version of their products to use the library. For this and not the last packages in dependencies you need to use. Such as: Microsoft.Extensions.Logging is better to use 2.1.0, because NLog requires a minimum of it.

Translated by Google Translate.

**Comment by Donkie** [comment]
I'm sorry but I don't really understand what you mean. Is 2.1 fine for you, or should I go with 2.0?

**Comment by VirRus77** [comment]
I apologize for being misleading. I meant that you do not need to take the latest version of net core. It is necessary to adhere to the minimum necessary.
Example: Having a project on net core 2.0, I can not use the library for net core 2.1 and higher. Accordingly, the above term is translated: "Take the minimum necessary version of the framework."
Also in the new version of the project there is the ability to do multi-target.
https://weblog.west-wind.com/posts/2017/jun/22/multitargeting-and-porting-a-net-library-to-net-core-20
Translated by Google Translate.

**Comment by Donkie** [comment]
Alright, I understand. It now targets 2.0.

**Pull request closed without merging**
