### PR TITLE
My latest changes.

### PR DESCRIPTION
**Pull request by VirRus77**
Very big refactoring.
Type 1 shapefix fixed.
Shaped type 2 added.

### CODE REVIEW

**Comment by VirRus77** [comment]
Always structure the project (folders). This will help when in a solution of 100 or more projects.

**Comment by Donkie** [comment]
Can you rebase this so it only contains the last commit?

**Comment by VirRus77** [comment]
Complete.

**Comment by Donkie** [comment]
Many good stuff, good job! Some remarks I'd like you to answer or fix before I merge:

* In `FileContainer.cs` you both have the ILogger as a field, and you pass it into the methods as a parameter. I think you should choose either one and stick with it. (imo use the field that's set in the constructor for cleaner code)
* Why did you put `ReadInt32` in an extension, `I3DDecryptorExtensions`. Why not directly in the `I3DDecryptor` class?
* Why did you split `I3DDecryptor` into two partial classes? There seems to be duplicated code between them, is this a mistake?
* I think it's a lot more optimized to keep the buffer as a static class field than creating a new buffer each time in the `I3DDecryptor`. There is no point in the data in it intact.
* Why is `I3DDecryptorStream` a "Tool" but the `I3DDecryptor` is not?
* If you can, it would be nice if you could comment some more what is going on in `Entity`, it is not very obvious from just reading the code.

**Comment by VirRus77** [comment]
FileContainer.cs fixed.
I3DDecryptor is its main task to unscramble what was offered to it. He does not need knowledge about Stream. Accordingly, I divided the functionality of I3DDecryptor into 2 files, so as not to accidentally clean up the necessary one.
Static variables are evil, which is permissible in very extreme cases. Because if the class is called in a multi-thread, the static variable will be at the mercy of several threads. And the result is not predictable. Accordingly, you need to write code, as if it would be called in multi-threads.
I3DDecryptorStream removed as unnecessary.
Entity - a kind of header for each entry in the file, read once. His task is to store the key index (read only this record without decrypting the contents of the records), the offset of the record in the file, and the size of the record. This reduces the memory used and allows you to read specific entries of the desired type.

Translated by Google Translate.

**Comment by VirRus77** [comment]
The I3Decriptor carries a logical rationale: in one part, working with the key itself, in the other, working with the data key.
Accordingly, the Load method in ShapesFile is left temporarily. In the future, it will be deleted and will need to work only with Entity. Because only this feature allows you to download information from cards using small memory. How I use: https://github.com/VirRus77/CourseplayEditor/blob/d1547fd2d1ea3c95a59c92cc60a469e1610bb33a/CourseplayEditor/ViewModel/MainWindowViewModel.cs#L162

**Comment by Donkie** [comment]
I see, didn't think about the memory aspects. Thanks for cleaning up the other things, Good job!

**Pull request merged**
